local palettes = {
    light = {
        canvas = "#f5f7f8",
        surface = "#edeff1",
        overlay = "#e8e9eb",
        text = "#241523",
        text_muted = "#746c75",
        border = "#cdd4dc",
        input = "#c0c9d4",
        accent = "#2672af",
        accent_fg = "#fffaff",
        secondary = "#e4ecf2",
        muted = "#e8eff4",
        muted_fg = "#6f6873",
        error = "#fb2c36",
        error_fg = "#c10007",
        error_surface = "#f5e6e9",
        warning = "#fe9a00",
        warning_fg = "#b74b00",
        warning_surface = "#f6efe4",
        update_fg = "#194a72",
        update_surface = "#d4e1ed",
        accent_surface = "#d8e4ee",
        message_surface = "#d0dfeb",
        message_action = "#0a6f75",
        message_action_hover = "#096267",
        code = "#f0f1f3",
        sidebar = "#e4ecf2",
        selection = "#d0dfeb",
        ansi_black = "#1f1f21",
    },
    dark = {
        canvas = "#17212b",
        surface = "#333b45",
        overlay = "#414851",
        text = "#fffaff",
        text_muted = "#8d8f97",
        border = "#405567",
        input = "#4f677b",
        accent = "#70b9ee",
        accent_fg = "#241523",
        secondary = "#293f52",
        muted = "#233544",
        muted_fg = "#969ca6",
        error = "#fb414a",
        error_fg = "#ff6467",
        error_surface = "#3c2630",
        warning = "#fe9a00",
        warning_fg = "#ffb900",
        warning_surface = "#3c3424",
        update_fg = "#a2d2f4",
        update_surface = "#345269",
        accent_surface = "#324e66",
        message_surface = "#375871",
        message_action = "#5bd0d6",
        message_action_hover = "#6fd6db",
        code = "#252e38",
        sidebar = "#1e2d3b",
        selection = "#36566f",
        ansi_black = "#141415",
    },
}

local colors = palettes[vim.o.background]

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "t3-ocean"

local highlights = {
    Normal = { fg = colors.text, bg = colors.canvas },
    NormalNC = { fg = colors.text, bg = colors.canvas },
    NormalFloat = { fg = colors.text, bg = colors.surface },
    FloatBorder = { fg = colors.border, bg = colors.surface },
    FloatTitle = { fg = colors.accent, bg = colors.surface, bold = true },
    Cursor = { fg = colors.canvas, bg = colors.accent },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = colors.code },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = colors.error_surface },
    LineNr = { fg = colors.text_muted },
    CursorLineNr = { fg = colors.accent, bold = true },
    SignColumn = { fg = colors.text_muted, bg = colors.canvas },
    FoldColumn = { fg = colors.text_muted, bg = colors.canvas },
    Folded = { fg = colors.text_muted, bg = colors.muted },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    Search = { fg = colors.warning_fg, bg = colors.warning_surface },
    IncSearch = { fg = colors.accent_fg, bg = colors.warning },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = colors.accent_fg, bg = colors.error },
    MatchParen = { fg = colors.accent, bg = colors.accent_surface, bold = true },
    Pmenu = { fg = colors.text, bg = colors.surface },
    PmenuSel = { fg = colors.text, bg = colors.accent_surface, bold = true },
    PmenuSbar = { bg = colors.secondary },
    PmenuThumb = { bg = colors.input },
    PmenuMatch = { fg = colors.accent, bold = true },
    PmenuMatchSel = { fg = colors.accent, bg = colors.accent_surface, bold = true },
    StatusLine = { fg = colors.text, bg = colors.secondary },
    StatusLineNC = { fg = colors.text_muted, bg = colors.secondary },
    TabLine = { fg = colors.text_muted, bg = colors.sidebar },
    TabLineFill = { bg = colors.sidebar },
    TabLineSel = { fg = colors.text, bg = colors.accent_surface, bold = true },
    WinSeparator = { fg = colors.border },
    WinBar = { fg = colors.text, bold = true },
    WinBarNC = { fg = colors.text_muted },
    Directory = { fg = colors.accent },
    Title = { fg = colors.accent, bold = true },
    ErrorMsg = { fg = colors.error },
    WarningMsg = { fg = colors.warning },
    MoreMsg = { fg = colors.message_action },
    Question = { fg = colors.message_action },
    ModeMsg = { fg = colors.accent, bold = true },
    NonText = { fg = colors.text_muted },
    Whitespace = { fg = colors.border },
    SpecialKey = { fg = colors.text_muted },
    Conceal = { fg = colors.text_muted },
    QuickFixLine = { bg = colors.message_surface, bold = true },
    SpellBad = { undercurl = true, sp = colors.error },
    SpellCap = { undercurl = true, sp = colors.warning },
    SpellLocal = { undercurl = true, sp = colors.message_action },
    SpellRare = { undercurl = true, sp = colors.accent },

    Comment = { fg = colors.text_muted, italic = true },
    Constant = { fg = colors.message_action },
    String = { fg = colors.message_action },
    Character = { fg = colors.message_action_hover },
    Number = { fg = colors.warning },
    Boolean = { fg = colors.error_fg },
    Float = { link = "Number" },
    Identifier = { fg = colors.text },
    Function = { fg = colors.accent },
    Statement = { fg = colors.update_fg },
    Conditional = { link = "Statement" },
    Repeat = { link = "Statement" },
    Label = { fg = colors.message_action },
    Operator = { fg = colors.muted_fg },
    Keyword = { fg = colors.accent },
    Exception = { fg = colors.error_fg },
    PreProc = { fg = colors.warning_fg },
    Include = { fg = colors.accent },
    Define = { fg = colors.warning_fg },
    Macro = { fg = colors.warning },
    Type = { fg = colors.warning_fg },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = colors.message_action_hover },
    SpecialChar = { link = "Special" },
    Tag = { fg = colors.accent },
    Delimiter = { fg = colors.muted_fg },
    SpecialComment = { fg = colors.text_muted, bold = true },
    Debug = { fg = colors.error_fg },
    Underlined = { fg = colors.accent, underline = true },
    -- Neovim does not define these; the @markup.* links below depend on them.
    Bold = { bold = true },
    Italic = { italic = true },
    Strikethrough = { strikethrough = true },
    Ignore = { fg = colors.text_muted },
    Error = { fg = colors.error },
    Todo = { fg = colors.warning_fg, bg = colors.warning_surface, bold = true },

    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.accent },
    DiagnosticHint = { fg = colors.message_action },
    DiagnosticOk = { fg = colors.message_action_hover },
    DiagnosticVirtualTextError = { fg = colors.error_fg, bg = colors.error_surface },
    DiagnosticVirtualTextWarn = { fg = colors.warning_fg, bg = colors.warning_surface },
    DiagnosticVirtualTextInfo = { fg = colors.update_fg, bg = colors.update_surface },
    DiagnosticVirtualTextHint = { fg = colors.message_action, bg = colors.muted },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.accent },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.message_action },

    DiffAdd = { fg = colors.message_action, bg = colors.muted },
    DiffChange = { fg = colors.update_fg, bg = colors.update_surface },
    DiffDelete = { fg = colors.error_fg, bg = colors.error_surface },
    DiffText = { fg = colors.text, bg = colors.message_surface, bold = true },
    Added = { fg = colors.message_action },
    Changed = { fg = colors.update_fg },
    Removed = { fg = colors.error_fg },

    GitSignsAdd = { fg = colors.message_action },
    GitSignsChange = { fg = colors.accent },
    GitSignsDelete = { fg = colors.error },
    GitSignsCurrentLineBlame = { fg = colors.text_muted, italic = true },
    IndentBlanklineChar = { fg = colors.border },
    IndentBlanklineContextChar = { fg = colors.accent },
    IblIndent = { fg = colors.border },
    IblScope = { fg = colors.accent },
    MiniIndentscopeSymbol = { fg = colors.accent },

    BlinkCmpMenu = { fg = colors.text, bg = colors.surface },
    BlinkCmpMenuSelection = { fg = colors.text, bg = colors.accent_surface },
    BlinkCmpLabel = { fg = colors.text },
    BlinkCmpLabelMatch = { fg = colors.accent, bold = true },
    BlinkCmpLabelDeprecated = { fg = colors.text_muted, strikethrough = true },
    BlinkCmpKind = { fg = colors.message_action },
    BlinkCmpSource = { fg = colors.text_muted },
    BlinkCmpDoc = { fg = colors.text, bg = colors.surface },
    BlinkCmpDocBorder = { fg = colors.border, bg = colors.surface },
    BlinkCmpSignatureHelp = { fg = colors.text, bg = colors.surface },
    BlinkCmpSignatureHelpBorder = { fg = colors.border, bg = colors.surface },

    SnacksDashboardHeader = { fg = colors.accent, bold = true },
    SnacksDashboardKey = { fg = colors.warning },
    SnacksDashboardDesc = { fg = colors.text },
    SnacksDashboardIcon = { fg = colors.message_action },
    SnacksDashboardFooter = { fg = colors.text_muted, italic = true },
    SnacksPickerBorder = { fg = colors.border, bg = colors.surface },
    SnacksPickerTitle = { fg = colors.accent, bg = colors.surface, bold = true },
    SnacksPickerMatch = { fg = colors.accent, bold = true },
    SnacksPickerDir = { fg = colors.text_muted },
    SnacksPickerSelected = { bg = colors.accent_surface },
    SnacksIndent = { fg = colors.border },
    SnacksIndentScope = { fg = colors.accent },

    WhichKey = { fg = colors.accent },
    WhichKeyGroup = { fg = colors.message_action },
    WhichKeyDesc = { fg = colors.text },
    WhichKeySeparator = { fg = colors.text_muted },
    WhichKeyNormal = { fg = colors.text, bg = colors.surface },
    NoiceCmdlinePopup = { fg = colors.text, bg = colors.surface },
    NoiceCmdlinePopupBorder = { fg = colors.border, bg = colors.surface },
    NoiceCmdlineIcon = { fg = colors.accent },
    LazyButton = { fg = colors.text, bg = colors.secondary },
    LazyButtonActive = { fg = colors.accent_fg, bg = colors.accent, bold = true },
    LazyH1 = { fg = colors.accent_fg, bg = colors.accent, bold = true },
    MasonHeader = { fg = colors.accent_fg, bg = colors.accent, bold = true },
    MasonHighlight = { fg = colors.accent },
    TroubleNormal = { fg = colors.text, bg = colors.canvas },
    TroubleText = { fg = colors.text },
    TroubleCount = { fg = colors.accent, bg = colors.accent_surface },

    RenderMarkdownH1Bg = { bg = colors.accent_surface },
    RenderMarkdownH2Bg = { bg = colors.message_surface },
    RenderMarkdownH3Bg = { bg = colors.update_surface },
    RenderMarkdownCode = { bg = colors.code },
    RenderMarkdownCodeInline = { bg = colors.code },
    RenderMarkdownBullet = { fg = colors.accent },
    RenderMarkdownLink = { fg = colors.message_action },
    RenderMarkdownUnchecked = { fg = colors.text_muted },
    RenderMarkdownChecked = { fg = colors.message_action },
}

local links = {
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = "Special",
    ["@variable.parameter"] = "Identifier",
    ["@variable.member"] = "Identifier",
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Special",
    ["@module"] = "Include",
    ["@string"] = "String",
    ["@string.escape"] = "SpecialChar",
    ["@character"] = "Character",
    ["@number"] = "Number",
    ["@boolean"] = "Boolean",
    ["@function"] = "Function",
    ["@function.builtin"] = "Special",
    ["@function.call"] = "Function",
    ["@function.method"] = "Function",
    ["@constructor"] = "Type",
    ["@keyword"] = "Keyword",
    ["@keyword.function"] = "Keyword",
    ["@keyword.return"] = "Keyword",
    ["@keyword.operator"] = "Operator",
    ["@operator"] = "Operator",
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@property"] = "Identifier",
    ["@attribute"] = "PreProc",
    ["@punctuation.delimiter"] = "Delimiter",
    ["@punctuation.bracket"] = "Delimiter",
    ["@punctuation.special"] = "Special",
    ["@comment"] = "Comment",
    ["@comment.todo"] = "Todo",
    ["@markup.heading"] = "Title",
    ["@markup.strong"] = "Bold",
    ["@markup.italic"] = "Italic",
    ["@markup.strikethrough"] = "Strikethrough",
    ["@markup.link"] = "Underlined",
    ["@markup.link.url"] = "Underlined",
    ["@markup.raw"] = "String",
    ["@markup.raw.block"] = "String",
    ["@markup.list"] = "Special",
    ["@diff.plus"] = "Added",
    ["@diff.delta"] = "Changed",
    ["@diff.minus"] = "Removed",
    ["@lsp.type.class"] = "Type",
    ["@lsp.type.decorator"] = "PreProc",
    ["@lsp.type.enum"] = "Type",
    ["@lsp.type.enumMember"] = "Constant",
    ["@lsp.type.function"] = "Function",
    ["@lsp.type.interface"] = "Type",
    ["@lsp.type.macro"] = "Macro",
    ["@lsp.type.method"] = "Function",
    ["@lsp.type.namespace"] = "Include",
    ["@lsp.type.parameter"] = "Identifier",
    ["@lsp.type.property"] = "Identifier",
    ["@lsp.type.struct"] = "Structure",
    ["@lsp.type.type"] = "Type",
    ["@lsp.type.typeParameter"] = "Typedef",
    ["@lsp.type.variable"] = "Identifier",
}

for group, highlight in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, highlight)
end

for group, target in pairs(links) do
    vim.api.nvim_set_hl(0, group, { link = target })
end

local terminal_colors = {
    colors.ansi_black,
    "#ff2e3f",
    "#0dbe4e",
    "#ffca00",
    "#009fff",
    "#c635e4",
    "#08c0ef",
    "#c6c6c8",
    colors.ansi_black,
    "#ff2e3f",
    "#0dbe4e",
    "#ffca00",
    "#009fff",
    "#c635e4",
    "#08c0ef",
    "#c6c6c8",
}

for index, color in ipairs(terminal_colors) do
    vim.g["terminal_color_" .. (index - 1)] = color
end
